# fly.toml app configuration file generated for uni-lab on 2026-06-04T13:17:43Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'uni-lab'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  DATA_DIR = '/data'
  PORT = '8080'

[[mounts]]
  source = 'unibursar_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
